### ISSUE TITLE
README.md install instructions

### ISSUE THREAD

**Issue by drf5n** [asascience-open/comt-ui#87]
You might add some notes on installation.
This works almost out of the box even without a webserver.  You need only:

```
 git clone git@github.com:asascience-open/comt-ui.git
 cd comt-ui
 edit index.html # to set wmsRoot = 'http://comt.sura.org/proxy_8080/wms/' ; singleTile = false;
```

... then point your browser at  file:///..../comt-ui/index.html

**Comment by brianmckenna** [comment]
@drf5n Thanks Dave, I'll add this

**Comment by brianmckenna** [comment]
https://github.com/asascience-open/comt-ui/commit/cba9102e32cada0b7087fc81a48efa6a961702ee
